### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by codediy** [badetitou/Pharo-LanguageServer#1]
install but can not use.
![image](https://user-images.githubusercontent.com/20250924/115947232-e2de5b80-a4f8-11eb-959e-d72fac161f11.png)
![image](https://user-images.githubusercontent.com/20250924/115947247-fab5df80-a4f8-11eb-875c-678850c3145c.png)
![image](https://user-images.githubusercontent.com/20250924/115947258-0dc8af80-a4f9-11eb-8a89-fcf11af94179.png)

**Comment by badetitou** [comment]
Hello

Your bug was introduced in previous version (v1.1.1). 
I just release v1.1.2 that fixed it

It was a missing dependency to a logger we use to improve our extension... And it broke it 😭 

Please, download last version image (v1.1.2), or download again the last continuous image
