### ISSUE TITLE
Remove PLS?

### ISSUE THREAD

**Issue by gamebox** [badetitou/Pharo-LanguageServer#10]
I'm new to Pharo/SmallTalk and not familiar with Metacello, and the docs are kind of opaque.  I would like to install PLS from my image since it causes frequent errors and a lot of trash in my transcript.  How can I remove the baseline?

**Comment by badetitou** [comment]
Hello, I don't understand your problem. 
Would you like to uninstall the Pharo Language Server?

Can you unload all the packages with Iceberg?
There is no existing way to easily unload the project.

**Comment by gamebox** [comment]
Thanks for the advice. Your extension is a great choice for those new to the ST ecosystem (which seems to have a lot of tribal knowledge and half-documented aspects), but it does occasionally have some issues with synchronization with the image and the UI.  So it would be great to document how to remove PLS from the image for those who are new around here ☺️.

I'll take your advice and look up Iceberg and figure out how to remove.  Thanks again.
