### ISSUE TITLE
Can't load/import Moose64/Pharo64 v4.0.3 images

### ISSUE THREAD

**Issue by larsw** [badetitou/Pharo-LanguageServer#12]
Hi,

I've downloaded the release, unzipped it, and tried both to Launch from Disk and Import in the Pharo Launcher, but I'm getting the following error message:

```
Error downloading 'https://files.pharo.org/get-files/11/pharo64-linux-stable.zip'
404 Not Found
```

**Comment by badetitou** [comment]
Oo. I think it is an error with the launcher. 
Can you start a standard pharo image?

**Comment by badetitou** [comment]
In fact, I think I will remove this option. Release in interesting when using the companion VSCode extension where the script does everything. But from this repository, manual loading is better I think so
