### ISSUE TITLE
DAPServer needs method #findCloseBracesFor: startIndex in String instance side and  it's not included in #DAP group,  PharoDAP package

### ISSUE THREAD

**Issue by jmari** [badetitou/Pharo-LanguageServer#6]
It is in the PharoLanguageServer package so when you install only  DAP Server using DAP group, this method is not installed and it is sended by DAP Server>>extractRequestFrom:

**Comment by badetitou** [comment]
Hello, 

I have fixed this in https://github.com/badetitou/Pharo-LanguageServer/commit/602e7dae8d4f676c695cedbbea2c47aa5d123be2

Please check the problem is gone.
If not, you can reopen the issue :-)
